export const SEARCH_FOCUS = 'header/search_focus'
export const SEARCH_BLUR = 'header/search_blur'
export const GET_LIST = 'header/get_list'
export const HOT_ENTER = 'header/hot_enter'
export const HOT_LEAVE = 'header/hot_leave'
export const CHANGE_HOT = 'header/change_hot'